name: Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:23.04
    steps:
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y --no-install-recommends \
            desktop-file-utils \
            fuse3 \
            gcc \
            gettext \
            gnome-desktop-testing \
            gtk-doc-tools \
            libcap2-bin \
            libflatpak-dev \
            libfontconfig1-dev \
            libfuse3-dev \
            libgdk-pixbuf-2.0-dev \
            libgeoclue-2-dev \
            libglib2.0-dev \
            libjson-glib-dev \
            libpipewire-0.3-dev \
            libportal-dev \
            libsystemd-dev \
            llvm \
            meson \
            python3-gi \
            shared-mime-info

      - name: Install dependencies for doc builds
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get install -y --no-install-recommends \
            ca-certificates \
            git \
            python3-sphinx \
            python3-sphinx-rtd-theme

      - name: Check out xdg-desktop-portal
        uses: actions/checkout@v3

      - name: Build docs
        run: |
          meson setup builddir -Ddocumentation=enabled
          meson compile -C builddir

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builddir/doc/html/
          destination_dir: ./
